[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200

# Handle Next.js pages and static files
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# Handle all other routes (SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
